name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-escript:
    name: Build escripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.13"
            otp_release: "24"

          - elixir: "1.14"
            otp_release: "25"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Install dependencies
      run: mix deps.get
    - name: Test
      run: mix test
    - name: Build escript
      run: mix escript.build
    - name: Rename escript
      run: "mv smppsend smppsend-${{ matrix.otp_release }}"
    - uses: actions/upload-artifact@v3
      with:
        name: otp-${{ matrix.otp_release }}
        path: smppsend-${{ matrix.otp_release }}

  build-burrito:
    name: Build Burrito executables
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14"
          otp-version: "25"

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1
      - name: Build Burrito
        run: ./burrito/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: burrito-images
          path: burrito_out/*

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs:
      - build-escript
      - build-burrito
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: Precompiled `smppsend` for the latest OTP versions
        files: |
          otp-*/smppsend-*
          burrito-images/*
